#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sphinx Configuration File
Project ID: Image Processing App 20251119
Author: The-Sage-Mage

Configuration file for Sphinx documentation builder.
"""

import os
import sys
from pathlib import Path

# Add the project root to the Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

# -- Project information -----------------------------------------------------

project = 'Image Processing App'
copyright = '2024, The-Sage-Mage LLC'
author = 'The-Sage-Mage'
version = '1.0.0'
release = '1.0.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',           # Include documentation from docstrings
    'sphinx.ext.autosummary',       # Generate autodoc summaries
    'sphinx.ext.viewcode',          # Add links to highlighted source code
    'sphinx.ext.napoleon',          # Support for Google and NumPy style docstrings
    'sphinx.ext.intersphinx',       # Link to other project's documentation
    'sphinx.ext.todo',              # Support for todo items
    'sphinx.ext.coverage',          # Documentation coverage statistics
    'sphinx.ext.mathjax',           # Render math via JavaScript
    'sphinx.ext.ifconfig',          # Include content based on config
    'sphinx.ext.githubpages',       # Publish HTML docs in GitHub Pages
    'sphinxcontrib.mermaid',        # Mermaid diagrams support
    'sphinx_rtd_theme',             # Read the Docs theme
    'sphinx.ext.doctest',           # Test snippets in documentation
]

# Napoleon settings for Google/NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Add any paths that contain templates here, relative to this directory
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'venv*',
    '__pycache__',
    '*.pyc',
    '.git',
    '.github',
    '.vscode',
    'tests',
]

# The suffix(es) of source filenames
source_suffix = {
    '.rst': None,
    '.md': 'markdown',
}

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Theme options
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'analytics_anonymize_ip': False,
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980b9',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# Custom sidebar templates
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

# HTML title
html_title = f"{project} v{version}"

# HTML short title
html_short_title = f"{project}"

# HTML favicon
html_favicon = None

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer
html_show_copyright = True

# If true, an OpenSearch description file will be output
html_use_opensearch = ''

# Output file base name for HTML help builder
htmlhelp_basename = 'ImageProcessingAppdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper')
    'papersize': 'letterpaper',
    
    # The font size ('10pt', '11pt' or '12pt')
    'pointsize': '10pt',
    
    # Additional stuff for the LaTeX preamble
    'preamble': '',
    
    # Latex figure (float) alignment
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, 'ImageProcessingApp.tex', 'Image Processing App Documentation',
     'The-Sage-Mage', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page
man_pages = [
    (master_doc, 'imageprocessingapp', 'Image Processing App Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (master_doc, 'ImageProcessingApp', 'Image Processing App Documentation',
     author, 'ImageProcessingApp', 'Advanced image processing application.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
    'sklearn': ('https://scikit-learn.org/stable/', None),
    'opencv': ('https://docs.opencv.org/4.x/', None),
    'pillow': ('https://pillow.readthedocs.io/en/stable/', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# -- Options for autodoc extension -------------------------------------------

# This value controls how to represent typehints
autodoc_typehints = 'description'

# This value controls whether to document class constructors separately
autodoc_class_signature = 'mixed'

# Controls whether to include type annotations in description signatures
autodoc_typehints_description_target = 'documented'

# Include both the class' and the __init__ method's docstring
autoclass_content = 'both'

# Default options for autodoc
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# -- Options for autosummary extension ---------------------------------------

# Generate autosummary pages
autosummary_generate = True

# Include autosummary in generated documentation
autosummary_imported_members = True

# -- Custom configuration ----------------------------------------------------

# Add custom CSS
def setup(app):
    """Add custom CSS and JavaScript."""
    app.add_css_file('custom.css')

# Suppress warnings for external links
nitpicky = False

# Pattern for suppressing warnings
nitpick_ignore = [
    ('py:class', 'typing.Any'),
    ('py:class', 'typing.Optional'),
    ('py:class', 'typing.Union'),
    ('py:class', 'typing.Dict'),
    ('py:class', 'typing.List'),
    ('py:class', 'typing.Tuple'),
]

# Enable numbered figures
numfig = True

# Figure, table and code-block numbering
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': 'Section %s',
}

# Maximum depth for table of contents
toctree_maxdepth = 3